services:
  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-${DOCKER_PROJECT_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ./.docker/nginx/logs:/var/log/nginx
    ports:
      - ${HOST_FRONTEND_PORT}:80
    env_file:
      - ./.env
    networks:
      - default

  ####################################################################################################
  # Vue
  ####################################################################################################
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    container_name: frontend-${DOCKER_PROJECT_NAME}
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - default

  ####################################################################################################
  # Laravel
  ####################################################################################################
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: backend-${DOCKER_PROJECT_NAME}
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend
      - /var/www/backend/vendor
    env_file:
      - ./backend/.env

  ####################################################################################################
  # DB
  ####################################################################################################
  db:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    container_name: db-${DOCKER_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - ${HOST_DB_PORT}:5432
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    env_file:
      - ./backend/.env
    networks:
      - default

volumes:
  db:
    external: true

networks:
  default:
    driver: bridge
